[package]
name = "ms-package-fuzz"
version = "0.1.0"
edition = "2024"
rust-version = "1.99"
publish = false

[workspace]

[dependencies]
honggfuzz = "=0.5.62"
ms-package = { path = ".." }
archive-core = { package = "caddy-archive-core", version = "0.1.0" }

zip = { version = "2.4", default-features = false }
msi = { package = "caddy-msi", version = "=0.10.0" }
sha2 = "0.10"
base64 = "0.22"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[profile.release]
debug = 1
overflow-checks = true
